import js from "@eslint/js";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import globals from "globals";

export default [
	js.configs.all,
	...tseslint.configs.recommended,
	{
		files: ["src/**/*.{js,jsx,ts,tsx}"],
		ignores: ["dist"],
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: "module",
			parserOptions: {
				ecmaFeatures: {
					jsx: true
				}
			},
			globals: {
				...globals.browser,
				...globals.node,
				Atomics: "readonly",
				SharedArrayBuffer: "readonly",
				PLATFORM: "readonly",
				APP: "readonly",
				PROFILER: "readonly",
				DEBUG: "readonly",
				NodeJS: "readonly",
				plist: "readonly",
			},
		},
		plugins: {
			react
		},
		rules: {
			"no-undef": "error",
			"no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrors: "none" }],
			"default-case": "warn",
			// TypeScript rules - all off
			"@typescript-eslint/no-unused-vars": "off",
			"@typescript-eslint/no-require-imports": "off",
			"@typescript-eslint/no-var-requires": "off",
			"@typescript-eslint/typedef": "off",
			"@typescript-eslint/no-explicit-any": "off",
			"@typescript-eslint/explicit-function-return-type": "off",
			"@typescript-eslint/explicit-member-accessibility": "off",
			"@typescript-eslint/no-empty-object-type": "off",
			"@typescript-eslint/no-unsafe-declaration-merging": "off",
			"@typescript-eslint/consistent-type-definitions": "off",
			"@typescript-eslint/no-inferrable-types": "off",
			"@typescript-eslint/no-empty-function": "off",
			"@typescript-eslint/no-unsafe-function-type": "off",
			"@typescript-eslint/array-type": "off",
			"@typescript-eslint/consistent-generic-constructors": "off",
			"@typescript-eslint/ban-ts-comment": "off",
			"@typescript-eslint/no-this-alias": "off",
			"@typescript-eslint/class-literal-property-style": "off",
			"@typescript-eslint/prefer-for-of": "off",
			"@typescript-eslint/consistent-indexed-object-style": "off",
			"@typescript-eslint/no-non-null-assertion": "off",
			"@typescript-eslint/adjacent-overload-signures": "off",
			"@typescript-eslint/consistent-return": "off",
			"@typescript-eslint/default-param-last": "off",
			"@typescript-eslint/no-floating-promises": "off",
			"@typescript-eslint/no-misused-promises": "off",
			// JS rules - all off
			"no-implicit-globals": "off",
			"no-magic-numbers": "off",
			"curly": "off",
			"one-var": "off",
			"no-plusplus": "off",
			"id-length": "off",
			"max-params": "off",
			"multiline-comment-style": "off",
			"sort-keys": "off",
			"capitalized-comments": "off",
			"prefer-const": "off",
			"func-style": "off",
			"max-statements": "off",
			"no-param-reassign": "off",
			"vars-on-top": "off",
			"no-ternary": "off",
			"sort-imports": "off",
			"no-underscore-dangle": "off",
			"no-useless-assignment": "off",
			"prefer-template": "off",
			"func-names": "off",
			"no-inline-comments": "off",
			"line-comment-position": "off",
			"max-lines-per-function": "off",
			"no-empty-function": "off",
			"no-negated-condition": "off",
			"no-bitwise": "off",
			"no-continue": "off",
			"no-undefined": "off",
			"class-methods-use-this": "off",
			"no-implicit-coercion": "off",
			"no-nested-ternary": "off",
			"complexity": "off",
			"consistent-this": "off",
			"radix": "off",
			"init-declarations": "off",
			"sort-vars": "off",
			"prefer-named-capture-group": "off",
			"require-unicode-regexp": "off",
			"no-console": "off",
			"prefer-destructuring": "off",
			"prefer-spread": "off",
			"no-useless-constructor": "off",
			"max-lines": "off",
			"no-shadow": "off",
			"no-warning-comments": "off",
			"no-await-in-loop": "off",
			"max-classes-per-file": "off",
			"no-duplicate-imports": "off",
			"prefer-exponentiation-operator": "off",
			"consistent-return": "off",
			"no-useless-escape": "off",
			"default-param-last": "off",
			"no-case-declarations": "off",
			"no-extra-label": "off",
			"no-use-before-define": "off",
			"no-var": "off",
			"eqeqeq": "off",
			"no-eq-null": "off",
			"camelcase": "off",
			"object-shorthand": "off",
			"arrow-body-style": "off",
			"no-useless-return": "off",
			"guard-for-in": "off",
			"no-lonely-if": "off",
			"no-extra-boolean-cast": "off",
			"no-else-return": "off",
			"prefer-object-spread": "off",
			"logical-assignment-operators": "off",
			"no-throw-literal": "off",
			"no-labels": "off",
			"no-empty": "off",
			"no-regex-spaces": "off",
			"grouped-accessor-pairs": "off",
			"require-await": "off"
		}
	}
];
